// ─── Mock Package Data ────────────────────────────────────────────────────────
export const packages = [
  {
    id: '1',
    title: 'Romantic Room Decoration',
    slug: 'romantic-room-decoration',
    category: 'Anniversary',
    subCategory: 'Room Decoration',
    price: 2499,
    originalPrice: 2999,
    badges: ['Best Seller'],
    description: 'Transform your bedroom into a dreamy romantic paradise with our signature rose petal and balloon setup. Perfect for anniversaries and surprise proposals.',
    whatsIncluded: [
      '50 premium latex balloons',
      'Rose petal bed decoration',
      '3-metre fairy lights string',
      'Scented candles (set of 12)',
      'Heart-shaped balloon cluster',
      'Custom welcome banner',
      'Disposable camera for memories',
    ],
    customizationOptions: { colors: ['#FF0000','#FF69B4','#FFC0CB','#9B59B6','#FFFFFF'] },
    images: [
      'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&q=80',
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 248,
    popularity: 95,
    faqs: [
      { q: 'How long does setup take?', a: 'Our team typically completes setup in 45–60 minutes.' },
      { q: 'Can I customise the colour scheme?', a: 'Yes! Choose from our palette during booking.' },
      { q: 'Do you provide same-day service?', a: 'Yes, book before 2 PM for same-day delivery.' },
    ],
  },
  {
    id: '2',
    title: 'Birthday Balloon Blast',
    slug: 'birthday-balloon-blast',
    category: 'Birthday',
    subCategory: 'Balloon Arch',
    price: 1799,
    originalPrice: 2199,
    badges: ['Trending'],
    description: 'An epic balloon arch setup that makes for the most Instagram-worthy birthday photos. Includes a vibrant mix of helium and latex balloons.',
    whatsIncluded: [
      'Grand balloon arch (8 ft)',
      '100 mixed latex balloons',
      '20 helium balloons with ribbons',
      '"Happy Birthday" foil banner',
      'Balloon column (pair)',
      'Party poppers (set of 10)',
    ],
    customizationOptions: { colors: ['#FFD700','#FF4500','#00BFFF','#7FFF00','#FF69B4','#9B59B6'] },
    images: [
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
      'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 183,
    popularity: 88,
    faqs: [
      { q: 'Are helium balloons included?', a: 'Yes, 20 helium balloons are part of this package.' },
      { q: 'What is the arch height?', a: 'Standard arch is 8 ft tall. Custom sizes available on request.' },
    ],
  },
  {
    id: '3',
    title: 'Car Boot Surprise Setup',
    slug: 'car-boot-surprise-setup',
    category: 'Birthday',
    subCategory: 'Car Boot',
    price: 1299,
    originalPrice: 1499,
    badges: [],
    description: 'Surprise your loved one with a magical car boot filled with balloons, fairy lights and heartfelt messages. A truly unforgettable moment.',
    whatsIncluded: [
      '60 latex balloons',
      '10 foil heart balloons',
      'Fairy lights (2 metres)',
      'Custom message board',
      'Personalised number plates',
      'Confetti scatter',
    ],
    customizationOptions: { colors: ['#FF0000','#FFD700','#FF69B4','#FFFFFF','#000000'] },
    images: [
      'https://images.unsplash.com/photo-1527525443983-6e60c75fff46?w=800&q=80',
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 97,
    popularity: 72,
    faqs: [
      { q: 'Will it damage my car interior?', a: 'We only use clean, non-marking materials. No damage guaranteed.' },
      { q: 'How long does setup take?', a: 'Approximately 30 minutes.' },
    ],
  },
  {
    id: '4',
    title: 'Baby Shower Bliss Package',
    slug: 'baby-shower-bliss-package',
    category: 'Baby Shower',
    subCategory: 'Table Setup',
    price: 3499,
    originalPrice: 3999,
    badges: ['Best Seller'],
    description: 'A pastel-perfect baby shower table and room decoration with teddy bears, clouds, and soft balloon clusters.',
    whatsIncluded: [
      'Full table decoration with runner',
      '80 pastel balloons',
      'Cloud balloon ceiling',
      '"It\'s a Baby!" foil banner',
      'Teddy bear centerpieces (×3)',
      'Flower garland draping',
      'Cake table setup',
    ],
    customizationOptions: { colors: ['#FFB6C1','#ADD8E6','#FFFACD','#E0FFE0','#DDA0DD'] },
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 312,
    popularity: 91,
    faqs: [
      { q: 'Can I choose blue or pink themed?', a: 'Absolutely! Select your preferred colour during booking.' },
      { q: 'Do you do gender reveal setups?', a: 'Yes, we offer gender-reveal add-ons. WhatsApp us for details.' },
    ],
  },
  {
    id: '5',
    title: 'Wedding Canopy Elegance',
    slug: 'wedding-canopy-elegance',
    category: 'Wedding',
    subCategory: 'Canopy',
    price: 8999,
    originalPrice: 10999,
    badges: ['Best Seller', 'Trending'],
    description: 'A luxurious floral canopy that turns your wedding into a fairytale. Draping fabric, fresh flowers, and warm Edison lights create an ethereal ambience.',
    whatsIncluded: [
      'Premium fabric canopy draping (10×10 ft)',
      'Fresh flower garlands',
      'Edison bulb string lights',
      'Pedestal flower stands (×4)',
      'Aisle petals decoration',
      'Backdrop flower wall (6×4 ft)',
      'On-site decorator for 3 hours',
    ],
    customizationOptions: { colors: ['#FFFFFF','#FFD700','#FF69B4','#E8D5B7','#C0C0C0'] },
    images: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=80',
      'https://images.unsplash.com/photo-1496843916299-590492c751f4?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 421,
    popularity: 98,
    faqs: [
      { q: 'Is this for indoor or outdoor weddings?', a: 'Both! We adjust setup based on your venue.' },
      { q: 'Can I add fresh flowers of my choice?', a: 'Yes, custom flowers are available at additional cost.' },
    ],
  },
  {
    id: '6',
    title: 'Engagement Stage Setup',
    slug: 'engagement-stage-setup',
    category: 'Engagement',
    subCategory: 'Stage Decor',
    price: 5999,
    originalPrice: 7499,
    badges: ['Trending'],
    description: 'Set the stage for your engagement with our premium backdrop, floral arrangements, and ambient lighting for a moment you will cherish forever.',
    whatsIncluded: [
      'LED-lit stage backdrop (8×6 ft)',
      'Floral arrangement clusters (×6)',
      'Ring-light centrepiece',
      'Sofa/couch decoration',
      '50 floral balloons',
      'Petal shower bag',
    ],
    customizationOptions: { colors: ['#FFD700','#FF0000','#FF69B4','#FFFFFF','#9B59B6'] },
    images: [
      'https://images.unsplash.com/photo-1604542031658-5799ca5d7936?w=800&q=80',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 156,
    popularity: 82,
    faqs: [
      { q: 'Can we add a custom name board?', a: 'Yes, personalised name banners are included.' },
      { q: 'What is the setup duration?', a: 'Setup takes approximately 90 minutes.' },
    ],
  },
  {
    id: '7',
    title: 'Birthday Photo Booth Setup',
    slug: 'birthday-photo-booth-setup',
    category: 'Birthday',
    subCategory: 'Photo Booth',
    price: 2999,
    originalPrice: 3499,
    badges: [],
    description: 'Create unforgettable photo memories with our vibrant photo booth complete with props, backdrop, and balloon surround.',
    whatsIncluded: [
      'Full photo booth backdrop (6×4 ft)',
      'Balloon surround framing',
      'Party props kit (20+ props)',
      'Ring-light stand',
      'LED star curtain',
      '"Birthday Star" personalised banner',
    ],
    customizationOptions: { colors: ['#FF4500','#FFD700','#FF69B4','#00CED1','#9B59B6'] },
    images: [
      'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 134,
    popularity: 79,
    faqs: [
      { q: 'Do you provide a photographer?', a: 'We provide the setup; you can hire a photographer separately.' },
      { q: 'Is this suitable for indoor use?', a: 'Yes, fully indoor-compatible.' },
    ],
  },
  {
    id: '8',
    title: 'Anniversary Canopy Dream',
    slug: 'anniversary-canopy-dream',
    category: 'Anniversary',
    subCategory: 'Canopy',
    price: 6999,
    originalPrice: 8999,
    badges: ['Best Seller'],
    description: 'Celebrate years of love under a stunning floral canopy designed exclusively for anniversary dinners and surprise celebrations.',
    whatsIncluded: [
      'Floral canopy (8×8 ft)',
      'Hanging fairy light curtain',
      'Rose petal pathway',
      'Dinner table setup for 2',
      'Wine glass decoration',
      '40 floating helium balloons',
      'Personalised photo collage frame',
    ],
    customizationOptions: { colors: ['#FF0000','#FF69B4','#FFFFFF','#C0C0C0','#FFD700'] },
    images: [
      'https://images.unsplash.com/photo-1496843916299-590492c751f4?w=800&q=80',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
      'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&q=80',
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 278,
    popularity: 90,
    faqs: [
      { q: 'Do you set up outdoors?', a: 'Yes, we serve both indoor and rooftop venues in Patna.' },
      { q: 'Can I add a cake delivery?', a: 'Yes! WhatsApp us to add a cake to your order.' },
    ],
  },
  {
    id: '9',
    title: 'Simple Birthday Room Decor',
    slug: 'simple-birthday-room-decor',
    category: 'Birthday',
    subCategory: 'Room Decoration',
    price: 999,
    originalPrice: 1199,
    badges: [],
    description: 'An affordable yet beautiful birthday room decoration that makes them feel special without breaking the bank.',
    whatsIncluded: [
      '30 colourful balloons',
      '"Happy Birthday" banner',
      'Star foil balloon',
      'Streamer rolls (×3)',
      'Balloon bouquet (×2)',
    ],
    customizationOptions: { colors: ['#FFD700','#FF4500','#00BFFF','#FF69B4','#7FFF00'] },
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
    ],
    rating: 4.3,
    reviewCount: 65,
    popularity: 60,
    faqs: [
      { q: 'Is this suitable for a kids party?', a: 'Absolutely! It is child-friendly and vibrant.' },
    ],
  },
  {
    id: '10',
    title: 'Royal Wedding Stage Decor',
    slug: 'royal-wedding-stage-decor',
    category: 'Wedding',
    subCategory: 'Stage Decor',
    price: 12999,
    originalPrice: 15999,
    badges: ['Best Seller'],
    description: 'A grand royal wedding stage with majestic floral backdrops, LED panels, and premium seating decoration fit for royalty.',
    whatsIncluded: [
      'Grand floral backdrop (12×8 ft)',
      'LED panel lighting rig',
      'Bride & Groom throne seating',
      'Aisle decoration (full length)',
      'Fresh marigold garlands',
      'Fog machine effects',
      'Dedicated decorator for 5 hours',
    ],
    customizationOptions: { colors: ['#FFD700','#FF0000','#FFFFFF','#FF69B4','#C0C0C0'] },
    images: [
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
      'https://images.unsplash.com/photo-1496843916299-590492c751f4?w=800&q=80',
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 389,
    popularity: 96,
    faqs: [
      { q: 'Can we customise the theme colour?', a: 'Yes, completely customisable theme and colours.' },
    ],
  },
  {
    id: '11',
    title: 'Baby Shower Balloon Cloud',
    slug: 'baby-shower-balloon-cloud',
    category: 'Baby Shower',
    subCategory: 'Balloon Arch',
    price: 2199,
    originalPrice: 2599,
    badges: ['Trending'],
    description: 'A dreamy balloon cloud arch in soft pastels for your baby shower celebration — perfect for photos and sweet memories.',
    whatsIncluded: [
      'Organic balloon arch (10 ft)',
      '120 pastel mixed balloons',
      '"Baby" letter balloons',
      'Cloud props (×4)',
      'Gold star confetti scatter',
      'Pastel streamer backdrop',
    ],
    customizationOptions: { colors: ['#FFB6C1','#ADD8E6','#FFFACD','#E0FFE0','#FFD700'] },
    images: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 201,
    popularity: 84,
    faqs: [
      { q: 'Is setup time included in the price?', a: 'Yes, full setup and cleanup are included.' },
    ],
  },
  {
    id: '12',
    title: 'Engagement Table Setup',
    slug: 'engagement-table-setup',
    category: 'Engagement',
    subCategory: 'Table Setup',
    price: 3299,
    originalPrice: 3999,
    badges: [],
    description: 'Elegant engagement dinner table setup with fresh flowers, candles, and personalised touches for a intimate celebration.',
    whatsIncluded: [
      'Floral centrepiece arrangement',
      'Candelabra with candles (×3)',
      'Table runner & linen',
      'Name card holders',
      'Balloon backdrop (4×3 ft)',
      'Personalised menus',
    ],
    customizationOptions: { colors: ['#FF0000','#FFD700','#FFFFFF','#FF69B4','#9B59B6'] },
    images: [
      'https://images.unsplash.com/photo-1604542031658-5799ca5d7936?w=800&q=80',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 112,
    popularity: 75,
    faqs: [
      { q: 'How many guests can this setup accommodate?', a: 'Typically designed for a table of 2, can be extended.' },
    ],
  },
];

// ─── Mock Reviews ────────────────────────────────────────────────────────────
export const reviews = [
  { id:'r1', packageId:'1', userName:'Priya Sharma',    rating:5, text:'Absolutely magical! The room looked like a dream. Our anniversary was unforgettable thanks to SDecor.', isVerified:true },
  { id:'r2', packageId:'1', userName:'Rahul Verma',     rating:5, text:'Perfect setup, on time, and the balloons were gorgeous. Highly recommend for any couple looking for a surprise!', isVerified:true },
  { id:'r3', packageId:'1', userName:'Neha Singh',      rating:4, text:'Loved the decoration! Only wish there were a few more candles. Overall a wonderful experience.', isVerified:true },
  { id:'r4', packageId:'2', userName:'Arjun Mehta',     rating:5, text:'The balloon arch was massive and so colourful. Everyone at the party loved it!', isVerified:true },
  { id:'r5', packageId:'2', userName:'Kavya Reddy',     rating:4, text:'Great value for money. Setup was quick and the team was professional.', isVerified:true },
  { id:'r6', packageId:'4', userName:'Sunita Devi',     rating:5, text:'The baby shower was perfect! Everyone kept complimenting the pastel cloud setup. SDecor exceeded expectations!', isVerified:true },
  { id:'r7', packageId:'4', userName:'Amit Kumar',      rating:5, text:'Booked for my wife\'s baby shower. The decorators were punctual and very professional. Absolutely loved it!', isVerified:true },
  { id:'r8', packageId:'5', userName:'Ritika Agarwal',  rating:5, text:'The canopy was breathtaking. Every photo looked like a magazine cover. Worth every rupee!', isVerified:true },
  { id:'r9', packageId:'5', userName:'Shivam Tiwari',   rating:5, text:'Professional team, stunning decor. Our guests were amazed. Will definitely book again!', isVerified:true },
  { id:'r10',packageId:'8', userName:'Pooja Gupta',     rating:5, text:'The canopy for our anniversary dinner was gorgeous. Romantic and memorable. Thank you SDecor!', isVerified:true },
  { id:'r11',packageId:'10',userName:'Manish Jha',      rating:5, text:'Grand stage setup that impressed every single guest. The team was very cooperative and on time.', isVerified:true },
  { id:'r12',packageId:'10',userName:'Ritu Pandey',     rating:5, text:'Best wedding decoration service in Patna without doubt! The stage was royal and majestic.', isVerified:true },
];

// ─── Sub-categories ──────────────────────────────────────────────────────────
export const subCategories = [
  { label:'Room Decoration', icon:'🛏️',  value:'Room Decoration'  },
  { label:'Balloon Arch',    icon:'🎈',  value:'Balloon Arch'     },
  { label:'Car Boot',        icon:'🚗',  value:'Car Boot'         },
  { label:'Canopy',          icon:'🌸',  value:'Canopy'           },
  { label:'Table Setup',     icon:'🕯️', value:'Table Setup'      },
  { label:'Stage Decor',     icon:'🎭',  value:'Stage Decor'      },
  { label:'Photo Booth',     icon:'📸',  value:'Photo Booth'      },
];

// ─── Categories ──────────────────────────────────────────────────────────────
export const categories = [
  { label:'Birthday',    value:'Birthday',    emoji:'🎂' },
  { label:'Anniversary', value:'Anniversary', emoji:'💍' },
  { label:'Baby Shower', value:'Baby Shower', emoji:'🍼' },
  { label:'Wedding',     value:'Wedding',     emoji:'💒' },
  { label:'Engagement',  value:'Engagement',  emoji:'💌' },
];
